sudo: false
language: python

python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"

env:
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.10,<1.11"
  - DJANGO="Django>=1.11,<2.0"

matrix:
  exclude:
    - env: DJANGO="Django>=1.8,<1.9"
      python: "3.6"
    - env: DJANGO="Django>=1.8,<1.9"
      python: "3.5"
    - env: DJANGO="Django>=1.9,<1.10"
      python: "3.3"
    - env: DJANGO="Django>=1.10,<1.11"
      python: "3.3"
    - env: DJANGO="Django>=1.11,<2.0"
      python: "3.3"

before_install: pip install --upgrade pip


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install $DJANGO
  - pip install -r requirements/dev.txt

# command to run tests, e.g. python setup.py test
script: coverage run --source=publisher tests/manage.py test myapp
after_script: coveralls
